//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Service.Resources.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that the background service {0} has failed execution with the message {1}..
        /// </summary>
        internal static string BackgroundService_FailureEmail_Body {
            get {
                return ResourceManager.GetString("BackgroundService_FailureEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Service : {0} has failed execution.
        /// </summary>
        internal static string BackgroundService_FailureEmail_Subject {
            get {
                return ResourceManager.GetString("BackgroundService_FailureEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///Dear User,
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Following Defect List:
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///&lt;table border=&quot;0&quot;&gt;
        ///&lt;tr&gt;
        ///&lt;td width=&quot;20px&quot;&gt;&lt;/td&gt;
        ///&lt;td&gt;Defect List :&lt;/td&gt;
        ///&lt;td&gt;{0}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;&lt;/td [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefectList_MailBody {
            get {
                return ResourceManager.GetString("DefectList_MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///&lt;td &gt;{0}&lt;/td&gt;
        ///&lt;td&gt;{1:dd-MMM-yyyy}&lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string DefectList_MailBody1 {
            get {
                return ResourceManager.GetString("DefectList_MailBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string DefectList_MailBody2 {
            get {
                return ResourceManager.GetString("DefectList_MailBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items in defect list {0} need to be rectified..
        /// </summary>
        internal static string DefectList_MailSubject {
            get {
                return ResourceManager.GetString("DefectList_MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect list {0}, defect item {1}, not yet rectified..
        /// </summary>
        internal static string DefectList_SMS {
            get {
                return ResourceManager.GetString("DefectList_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///Dear {0},
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Please be informed that the following milestone&apos;s estimated start/end date is approaching.
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Project Details:
        ///&lt;table border=&quot;0&quot;&gt;
        ///&lt;tr&gt;
        ///&lt;td width=&quot;20&quot;&gt;&lt;/td&gt;
        ///&lt;td&gt;Project Name:&lt;/td&gt;
        ///&lt;td&gt;{1}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Project_NotificationBody {
            get {
                return ResourceManager.GetString("Project_NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///&lt;td width=&quot;200&quot;&gt;{ObjectName}&lt;/td&gt;
        ///&lt;td width=&quot;130&quot;&gt;{EstimatedStart:dd-MMM-yyyy}&lt;/td&gt;
        ///&lt;td width=&quot;130&quot;&gt;{EstimatedEnd:dd-MMM-yyyy}&lt;/td&gt;
        ///&lt;td width=&quot;130&quot;&gt;{ActualStartText}&lt;/td&gt;
        ///&lt;td width=&quot;130&quot;&gt;{ActualEndText}&lt;/td&gt;
        ///&lt;td width=&quot;130&quot;&gt;{MilestoneProgress}&lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string Project_NotificationBody1 {
            get {
                return ResourceManager.GetString("Project_NotificationBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Project_NotificationBody2 {
            get {
                return ResourceManager.GetString("Project_NotificationBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated End Date ({0: dd-MMM-yy}) for Milestone {1} of Project {2} Approaching.
        /// </summary>
        internal static string Project_NotificationSMS {
            get {
                return ResourceManager.GetString("Project_NotificationSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Milestone&apos;s Estimated Start/End Date for Project {0} Approaching.
        /// </summary>
        internal static string Project_NotificationSubject {
            get {
                return ResourceManager.GetString("Project_NotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///Dear Budget Administrator,
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///The following line items have fallen below their threshold. Please seek funds 
        ///for readjustment or reallocation.
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///If [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Store_LowBudgetItemBody {
            get {
                return ResourceManager.GetString("Store_LowBudgetItemBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///&lt;td width=&quot;300px&quot;&gt;{0}&lt;/td&gt;
        ///&lt;td&gt;{2:#,##0.00}&lt;/td&gt;
        ///&lt;td&gt;{3:#,##0.00}&lt;/td&gt;
        ///&lt;td&gt;{4:#,##0.00}&lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string Store_LowBudgetItemBody1 {
            get {
                return ResourceManager.GetString("Store_LowBudgetItemBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Store_LowBudgetItemBody2 {
            get {
                return ResourceManager.GetString("Store_LowBudgetItemBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low budget notification for budget - {0}.
        /// </summary>
        internal static string Store_LowBudgetItemSubject {
            get {
                return ResourceManager.GetString("Store_LowBudgetItemSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///Dear Store Administrator,
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///The following inventory items have fallen below their threshold. Please 
        ///replenish these items.
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///&lt;table border=&quot;0&quot;&gt;
        ///&lt;tr&gt;
        ///&lt;td width=&quot;20px&quot;&gt;&lt;/td&gt;
        ///&lt;td&gt;Store Name:&lt;/td&gt;
        ///&lt;td&gt;{0}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Store_LowInventoryBody1 {
            get {
                return ResourceManager.GetString("Store_LowInventoryBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///&lt;td width=&quot;200px&quot;&gt;{Catalogue.ObjectName}&lt;/td&gt;
        ///&lt;td width=&quot;120px&quot;&gt;{Catalogue.UnitOfMeasure.ObjectName}&lt;/td&gt;
        ///&lt;td&gt;{TotalAvailableQuantity,25:#,##0.00}&lt;/td&gt;
        ///&lt;td&gt;{TotalPhysicalQuantity,25:#,##0.00}&lt;/td&gt;
        ///&lt;td&gt;{ReorderThreshold,25:#,##0.00}&lt;/td&gt;
        ///&lt;td&gt;{ReorderDefault,25:#,##0.00}&lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string Store_LowInventoryBody2 {
            get {
                return ResourceManager.GetString("Store_LowInventoryBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Store_LowInventoryBody3 {
            get {
                return ResourceManager.GetString("Store_LowInventoryBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Inventory Notification for store - {0}.
        /// </summary>
        internal static string Store_LowInventorySubject {
            get {
                return ResourceManager.GetString("Store_LowInventorySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Survey Admin,
        ///
        ///The survey has reached the reminder date set in the system.  You may wish to log into {0} for your further actions.
        ///
        ///Survey Name: {1}
        ///Survey Type:  {2}
        ///Survey Evaluation Period: {3} to {4}
        ///Survey Validity Period: {5} to {6}
        ///Survey Threshold: {7}
        ///
        ///Thank you.
        ///
        ///This is a computer-generated email, please do not reply to this email address..
        /// </summary>
        internal static string SurveyPlanner_NotifyReminder_Body {
            get {
                return ResourceManager.GetString("SurveyPlanner_NotifyReminder_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Reminder Date Reached).
        /// </summary>
        internal static string SurveyPlanner_NotifyReminder_Subject {
            get {
                return ResourceManager.GetString("SurveyPlanner_NotifyReminder_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Survey Admin,
        ///
        ///The survey has reached the threshold set in the system.  You may wish to log into {0} for your further actions.
        ///
        ///Survey Name: {1}
        ///Survey Type:  {2}
        ///Survey Evaluation Period: {3} to {4}
        ///Survey Validity Period: {5} to {6}
        ///Survey Threshold: {7}
        ///
        ///Thank you.
        ///
        ///This is a computer-generated email, please do not reply to this email address..
        /// </summary>
        internal static string SurveyPlanner_ThresholdNotification_Body {
            get {
                return ResourceManager.GetString("SurveyPlanner_ThresholdNotification_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Threshold Reached).
        /// </summary>
        internal static string SurveyPlanner_ThresholdNotification_Subject {
            get {
                return ResourceManager.GetString("SurveyPlanner_ThresholdNotification_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Survey Admin,
        ///
        ///The survey has reached the threshold and validity end date set in the system.  You may wish to log into {0} for your further actions.
        ///
        ///Survey Name: {1}
        ///Survey Type:  {2}
        ///Survey Evaluation Period: {3} to {4}
        ///Survey Validity Period: {5} to {6}
        ///Survey Threshold: {7}
        ///
        ///Thank you.
        ///
        ///This is a computer-generated email, please do not reply to this email address..
        /// </summary>
        internal static string SurveyPlanner_ThresholdValidityEndNotification_Body {
            get {
                return ResourceManager.GetString("SurveyPlanner_ThresholdValidityEndNotification_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Threshold &amp; Validity End Date Reached).
        /// </summary>
        internal static string SurveyPlanner_ThresholdValidityEndNotification_Subject {
            get {
                return ResourceManager.GetString("SurveyPlanner_ThresholdValidityEndNotification_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Survey Admin,
        ///
        ///The survey has reached the validity end date set in the system.  You may wish to log into {0} for your further actions.
        ///
        ///Survey Name: {1}
        ///Survey Type:  {2}
        ///Survey Evaluation Period: {3} to {4}
        ///Survey Validity Period: {5} to {6}
        ///Survey Threshold: {7}
        ///
        ///Thank you.
        ///
        ///This is a computer-generated email, please do not reply to this email address..
        /// </summary>
        internal static string SurveyPlanner_ValidityEndNotification_Body {
            get {
                return ResourceManager.GetString("SurveyPlanner_ValidityEndNotification_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Validity End Date Reached).
        /// </summary>
        internal static string SurveyPlanner_ValidityEndNotification_Subject {
            get {
                return ResourceManager.GetString("SurveyPlanner_ValidityEndNotification_Subject", resourceCulture);
            }
        }
    }
}
