//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4984.
// 
#pragma warning disable 1591

namespace LogicLayer.CRVTenderService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TenderServiceSoap", Namespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm")]
    public partial class TenderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetActiveCRVSerialNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmCRVSerialUsageOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTenderProjectRefNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFullTenderInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTenderNoOfContractsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloseTenderOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelTenderOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTenderVendorAwardStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupProjectInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateGroupProjectInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateGroupProjectContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateGroupProjectContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupProcurementInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateGroupProcurementInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateGroupProcurementContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateGroupProcurementContractOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TenderService() {
            this.Url = global::LogicLayer.Properties.Settings.Default.LogicLayer_CRVTenderService_TenderService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetActiveCRVSerialNumbersCompletedEventHandler GetActiveCRVSerialNumbersCompleted;
        
        /// <remarks/>
        public event ConfirmCRVSerialUsageCompletedEventHandler ConfirmCRVSerialUsageCompleted;
        
        /// <remarks/>
        public event UpdateTenderProjectRefNoCompletedEventHandler UpdateTenderProjectRefNoCompleted;
        
        /// <remarks/>
        public event GetFullTenderInfoCompletedEventHandler GetFullTenderInfoCompleted;
        
        /// <remarks/>
        public event GetTenderNoOfContractsCompletedEventHandler GetTenderNoOfContractsCompleted;
        
        /// <remarks/>
        public event CloseTenderCompletedEventHandler CloseTenderCompleted;
        
        /// <remarks/>
        public event CancelTenderCompletedEventHandler CancelTenderCompleted;
        
        /// <remarks/>
        public event UpdateTenderVendorAwardStatusCompletedEventHandler UpdateTenderVendorAwardStatusCompleted;
        
        /// <remarks/>
        public event GetGroupProjectInformationCompletedEventHandler GetGroupProjectInformationCompleted;
        
        /// <remarks/>
        public event UpdateGroupProjectInformationCompletedEventHandler UpdateGroupProjectInformationCompleted;
        
        /// <remarks/>
        public event CreateGroupProjectContractCompletedEventHandler CreateGroupProjectContractCompleted;
        
        /// <remarks/>
        public event UpdateGroupProjectContractCompletedEventHandler UpdateGroupProjectContractCompleted;
        
        /// <remarks/>
        public event GetGroupProcurementInformationCompletedEventHandler GetGroupProcurementInformationCompleted;
        
        /// <remarks/>
        public event UpdateGroupProcurementInformationCompletedEventHandler UpdateGroupProcurementInformationCompleted;
        
        /// <remarks/>
        public event CreateGroupProcurementContractCompletedEventHandler CreateGroupProcurementContractCompleted;
        
        /// <remarks/>
        public event UpdateGroupProcurementContractCompletedEventHandler UpdateGroupProcurementContractCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/GetActiveCRVSerialNumbe" +
            "rs", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetActiveCRVSerialNumbers(string systemcode) {
            object[] results = this.Invoke("GetActiveCRVSerialNumbers", new object[] {
                        systemcode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveCRVSerialNumbersAsync(string systemcode) {
            this.GetActiveCRVSerialNumbersAsync(systemcode, null);
        }
        
        /// <remarks/>
        public void GetActiveCRVSerialNumbersAsync(string systemcode, object userState) {
            if ((this.GetActiveCRVSerialNumbersOperationCompleted == null)) {
                this.GetActiveCRVSerialNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveCRVSerialNumbersOperationCompleted);
            }
            this.InvokeAsync("GetActiveCRVSerialNumbers", new object[] {
                        systemcode}, this.GetActiveCRVSerialNumbersOperationCompleted, userState);
        }
        
        private void OnGetActiveCRVSerialNumbersOperationCompleted(object arg) {
            if ((this.GetActiveCRVSerialNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveCRVSerialNumbersCompleted(this, new GetActiveCRVSerialNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/ConfirmCRVSerialUsage", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConfirmCRVSerialUsage(string systemcode, string CRVSerialNo, bool IsInUse) {
            object[] results = this.Invoke("ConfirmCRVSerialUsage", new object[] {
                        systemcode,
                        CRVSerialNo,
                        IsInUse});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmCRVSerialUsageAsync(string systemcode, string CRVSerialNo, bool IsInUse) {
            this.ConfirmCRVSerialUsageAsync(systemcode, CRVSerialNo, IsInUse, null);
        }
        
        /// <remarks/>
        public void ConfirmCRVSerialUsageAsync(string systemcode, string CRVSerialNo, bool IsInUse, object userState) {
            if ((this.ConfirmCRVSerialUsageOperationCompleted == null)) {
                this.ConfirmCRVSerialUsageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmCRVSerialUsageOperationCompleted);
            }
            this.InvokeAsync("ConfirmCRVSerialUsage", new object[] {
                        systemcode,
                        CRVSerialNo,
                        IsInUse}, this.ConfirmCRVSerialUsageOperationCompleted, userState);
        }
        
        private void OnConfirmCRVSerialUsageOperationCompleted(object arg) {
            if ((this.ConfirmCRVSerialUsageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmCRVSerialUsageCompleted(this, new ConfirmCRVSerialUsageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/UpdateTenderProjectRefN" +
            "o", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateTenderProjectRefNo(string systemcode, string CRVSerialNo, string refno) {
            object[] results = this.Invoke("UpdateTenderProjectRefNo", new object[] {
                        systemcode,
                        CRVSerialNo,
                        refno});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTenderProjectRefNoAsync(string systemcode, string CRVSerialNo, string refno) {
            this.UpdateTenderProjectRefNoAsync(systemcode, CRVSerialNo, refno, null);
        }
        
        /// <remarks/>
        public void UpdateTenderProjectRefNoAsync(string systemcode, string CRVSerialNo, string refno, object userState) {
            if ((this.UpdateTenderProjectRefNoOperationCompleted == null)) {
                this.UpdateTenderProjectRefNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTenderProjectRefNoOperationCompleted);
            }
            this.InvokeAsync("UpdateTenderProjectRefNo", new object[] {
                        systemcode,
                        CRVSerialNo,
                        refno}, this.UpdateTenderProjectRefNoOperationCompleted, userState);
        }
        
        private void OnUpdateTenderProjectRefNoOperationCompleted(object arg) {
            if ((this.UpdateTenderProjectRefNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTenderProjectRefNoCompleted(this, new UpdateTenderProjectRefNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/GetFullTenderInfo", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CRVTender GetFullTenderInfo(string systemcode, string CRVSerialNo) {
            object[] results = this.Invoke("GetFullTenderInfo", new object[] {
                        systemcode,
                        CRVSerialNo});
            return ((CRVTender)(results[0]));
        }
        
        /// <remarks/>
        public void GetFullTenderInfoAsync(string systemcode, string CRVSerialNo) {
            this.GetFullTenderInfoAsync(systemcode, CRVSerialNo, null);
        }
        
        /// <remarks/>
        public void GetFullTenderInfoAsync(string systemcode, string CRVSerialNo, object userState) {
            if ((this.GetFullTenderInfoOperationCompleted == null)) {
                this.GetFullTenderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFullTenderInfoOperationCompleted);
            }
            this.InvokeAsync("GetFullTenderInfo", new object[] {
                        systemcode,
                        CRVSerialNo}, this.GetFullTenderInfoOperationCompleted, userState);
        }
        
        private void OnGetFullTenderInfoOperationCompleted(object arg) {
            if ((this.GetFullTenderInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFullTenderInfoCompleted(this, new GetFullTenderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/GetTenderNoOfContracts", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> GetTenderNoOfContracts(string systemcode, string CRVSerialNo) {
            object[] results = this.Invoke("GetTenderNoOfContracts", new object[] {
                        systemcode,
                        CRVSerialNo});
            return ((System.Nullable<int>)(results[0]));
        }
        
        /// <remarks/>
        public void GetTenderNoOfContractsAsync(string systemcode, string CRVSerialNo) {
            this.GetTenderNoOfContractsAsync(systemcode, CRVSerialNo, null);
        }
        
        /// <remarks/>
        public void GetTenderNoOfContractsAsync(string systemcode, string CRVSerialNo, object userState) {
            if ((this.GetTenderNoOfContractsOperationCompleted == null)) {
                this.GetTenderNoOfContractsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTenderNoOfContractsOperationCompleted);
            }
            this.InvokeAsync("GetTenderNoOfContracts", new object[] {
                        systemcode,
                        CRVSerialNo}, this.GetTenderNoOfContractsOperationCompleted, userState);
        }
        
        private void OnGetTenderNoOfContractsOperationCompleted(object arg) {
            if ((this.GetTenderNoOfContractsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTenderNoOfContractsCompleted(this, new GetTenderNoOfContractsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/CloseTender", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CloseTender(string systemcode, string CRVSerialNo) {
            object[] results = this.Invoke("CloseTender", new object[] {
                        systemcode,
                        CRVSerialNo});
            return ((System.Nullable<int>)(results[0]));
        }
        
        /// <remarks/>
        public void CloseTenderAsync(string systemcode, string CRVSerialNo) {
            this.CloseTenderAsync(systemcode, CRVSerialNo, null);
        }
        
        /// <remarks/>
        public void CloseTenderAsync(string systemcode, string CRVSerialNo, object userState) {
            if ((this.CloseTenderOperationCompleted == null)) {
                this.CloseTenderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloseTenderOperationCompleted);
            }
            this.InvokeAsync("CloseTender", new object[] {
                        systemcode,
                        CRVSerialNo}, this.CloseTenderOperationCompleted, userState);
        }
        
        private void OnCloseTenderOperationCompleted(object arg) {
            if ((this.CloseTenderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloseTenderCompleted(this, new CloseTenderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/CancelTender", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CancelTender(string systemcode, string CRVSerialNo, string cancelreason) {
            object[] results = this.Invoke("CancelTender", new object[] {
                        systemcode,
                        CRVSerialNo,
                        cancelreason});
            return ((System.Nullable<int>)(results[0]));
        }
        
        /// <remarks/>
        public void CancelTenderAsync(string systemcode, string CRVSerialNo, string cancelreason) {
            this.CancelTenderAsync(systemcode, CRVSerialNo, cancelreason, null);
        }
        
        /// <remarks/>
        public void CancelTenderAsync(string systemcode, string CRVSerialNo, string cancelreason, object userState) {
            if ((this.CancelTenderOperationCompleted == null)) {
                this.CancelTenderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelTenderOperationCompleted);
            }
            this.InvokeAsync("CancelTender", new object[] {
                        systemcode,
                        CRVSerialNo,
                        cancelreason}, this.CancelTenderOperationCompleted, userState);
        }
        
        private void OnCancelTenderOperationCompleted(object arg) {
            if ((this.CancelTenderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelTenderCompleted(this, new CancelTenderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/UpdateTenderVendorAward" +
            "Status", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateTenderVendorAwardStatus(string systemcode, string CRVSerialNo, CRVTenderVendor v) {
            object[] results = this.Invoke("UpdateTenderVendorAwardStatus", new object[] {
                        systemcode,
                        CRVSerialNo,
                        v});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTenderVendorAwardStatusAsync(string systemcode, string CRVSerialNo, CRVTenderVendor v) {
            this.UpdateTenderVendorAwardStatusAsync(systemcode, CRVSerialNo, v, null);
        }
        
        /// <remarks/>
        public void UpdateTenderVendorAwardStatusAsync(string systemcode, string CRVSerialNo, CRVTenderVendor v, object userState) {
            if ((this.UpdateTenderVendorAwardStatusOperationCompleted == null)) {
                this.UpdateTenderVendorAwardStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTenderVendorAwardStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateTenderVendorAwardStatus", new object[] {
                        systemcode,
                        CRVSerialNo,
                        v}, this.UpdateTenderVendorAwardStatusOperationCompleted, userState);
        }
        
        private void OnUpdateTenderVendorAwardStatusOperationCompleted(object arg) {
            if ((this.UpdateTenderVendorAwardStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTenderVendorAwardStatusCompleted(this, new UpdateTenderVendorAwardStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/GetGroupProjectInformat" +
            "ion", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GroupProjectInformation GetGroupProjectInformation(string systemcode, string CRVSerialNo) {
            object[] results = this.Invoke("GetGroupProjectInformation", new object[] {
                        systemcode,
                        CRVSerialNo});
            return ((GroupProjectInformation)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupProjectInformationAsync(string systemcode, string CRVSerialNo) {
            this.GetGroupProjectInformationAsync(systemcode, CRVSerialNo, null);
        }
        
        /// <remarks/>
        public void GetGroupProjectInformationAsync(string systemcode, string CRVSerialNo, object userState) {
            if ((this.GetGroupProjectInformationOperationCompleted == null)) {
                this.GetGroupProjectInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupProjectInformationOperationCompleted);
            }
            this.InvokeAsync("GetGroupProjectInformation", new object[] {
                        systemcode,
                        CRVSerialNo}, this.GetGroupProjectInformationOperationCompleted, userState);
        }
        
        private void OnGetGroupProjectInformationOperationCompleted(object arg) {
            if ((this.GetGroupProjectInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupProjectInformationCompleted(this, new GetGroupProjectInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/UpdateGroupProjectInfor" +
            "mation", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateGroupProjectInformation(string systemcode, string CRVSerialNo, GroupProjectInformation gpi) {
            object[] results = this.Invoke("UpdateGroupProjectInformation", new object[] {
                        systemcode,
                        CRVSerialNo,
                        gpi});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateGroupProjectInformationAsync(string systemcode, string CRVSerialNo, GroupProjectInformation gpi) {
            this.UpdateGroupProjectInformationAsync(systemcode, CRVSerialNo, gpi, null);
        }
        
        /// <remarks/>
        public void UpdateGroupProjectInformationAsync(string systemcode, string CRVSerialNo, GroupProjectInformation gpi, object userState) {
            if ((this.UpdateGroupProjectInformationOperationCompleted == null)) {
                this.UpdateGroupProjectInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateGroupProjectInformationOperationCompleted);
            }
            this.InvokeAsync("UpdateGroupProjectInformation", new object[] {
                        systemcode,
                        CRVSerialNo,
                        gpi}, this.UpdateGroupProjectInformationOperationCompleted, userState);
        }
        
        private void OnUpdateGroupProjectInformationOperationCompleted(object arg) {
            if ((this.UpdateGroupProjectInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateGroupProjectInformationCompleted(this, new UpdateGroupProjectInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/CreateGroupProjectContr" +
            "act", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateGroupProjectContract(string systemcode, string CRVSerialNo, GProjectContract gpc) {
            object[] results = this.Invoke("CreateGroupProjectContract", new object[] {
                        systemcode,
                        CRVSerialNo,
                        gpc});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateGroupProjectContractAsync(string systemcode, string CRVSerialNo, GProjectContract gpc) {
            this.CreateGroupProjectContractAsync(systemcode, CRVSerialNo, gpc, null);
        }
        
        /// <remarks/>
        public void CreateGroupProjectContractAsync(string systemcode, string CRVSerialNo, GProjectContract gpc, object userState) {
            if ((this.CreateGroupProjectContractOperationCompleted == null)) {
                this.CreateGroupProjectContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateGroupProjectContractOperationCompleted);
            }
            this.InvokeAsync("CreateGroupProjectContract", new object[] {
                        systemcode,
                        CRVSerialNo,
                        gpc}, this.CreateGroupProjectContractOperationCompleted, userState);
        }
        
        private void OnCreateGroupProjectContractOperationCompleted(object arg) {
            if ((this.CreateGroupProjectContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateGroupProjectContractCompleted(this, new CreateGroupProjectContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/UpdateGroupProjectContr" +
            "act", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateGroupProjectContract(string systemcode, string CRVSerialNo, GProjectContract gpc) {
            object[] results = this.Invoke("UpdateGroupProjectContract", new object[] {
                        systemcode,
                        CRVSerialNo,
                        gpc});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateGroupProjectContractAsync(string systemcode, string CRVSerialNo, GProjectContract gpc) {
            this.UpdateGroupProjectContractAsync(systemcode, CRVSerialNo, gpc, null);
        }
        
        /// <remarks/>
        public void UpdateGroupProjectContractAsync(string systemcode, string CRVSerialNo, GProjectContract gpc, object userState) {
            if ((this.UpdateGroupProjectContractOperationCompleted == null)) {
                this.UpdateGroupProjectContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateGroupProjectContractOperationCompleted);
            }
            this.InvokeAsync("UpdateGroupProjectContract", new object[] {
                        systemcode,
                        CRVSerialNo,
                        gpc}, this.UpdateGroupProjectContractOperationCompleted, userState);
        }
        
        private void OnUpdateGroupProjectContractOperationCompleted(object arg) {
            if ((this.UpdateGroupProjectContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateGroupProjectContractCompleted(this, new UpdateGroupProjectContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/GetGroupProcurementInfo" +
            "rmation", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GroupProcurementInformation GetGroupProcurementInformation(string systemcode, string CRVSerialNo) {
            object[] results = this.Invoke("GetGroupProcurementInformation", new object[] {
                        systemcode,
                        CRVSerialNo});
            return ((GroupProcurementInformation)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupProcurementInformationAsync(string systemcode, string CRVSerialNo) {
            this.GetGroupProcurementInformationAsync(systemcode, CRVSerialNo, null);
        }
        
        /// <remarks/>
        public void GetGroupProcurementInformationAsync(string systemcode, string CRVSerialNo, object userState) {
            if ((this.GetGroupProcurementInformationOperationCompleted == null)) {
                this.GetGroupProcurementInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupProcurementInformationOperationCompleted);
            }
            this.InvokeAsync("GetGroupProcurementInformation", new object[] {
                        systemcode,
                        CRVSerialNo}, this.GetGroupProcurementInformationOperationCompleted, userState);
        }
        
        private void OnGetGroupProcurementInformationOperationCompleted(object arg) {
            if ((this.GetGroupProcurementInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupProcurementInformationCompleted(this, new GetGroupProcurementInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/UpdateGroupProcurementI" +
            "nformation", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateGroupProcurementInformation(string systemcode, string CRVSerialNo, GroupProcurementInformation gpi) {
            object[] results = this.Invoke("UpdateGroupProcurementInformation", new object[] {
                        systemcode,
                        CRVSerialNo,
                        gpi});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateGroupProcurementInformationAsync(string systemcode, string CRVSerialNo, GroupProcurementInformation gpi) {
            this.UpdateGroupProcurementInformationAsync(systemcode, CRVSerialNo, gpi, null);
        }
        
        /// <remarks/>
        public void UpdateGroupProcurementInformationAsync(string systemcode, string CRVSerialNo, GroupProcurementInformation gpi, object userState) {
            if ((this.UpdateGroupProcurementInformationOperationCompleted == null)) {
                this.UpdateGroupProcurementInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateGroupProcurementInformationOperationCompleted);
            }
            this.InvokeAsync("UpdateGroupProcurementInformation", new object[] {
                        systemcode,
                        CRVSerialNo,
                        gpi}, this.UpdateGroupProcurementInformationOperationCompleted, userState);
        }
        
        private void OnUpdateGroupProcurementInformationOperationCompleted(object arg) {
            if ((this.UpdateGroupProcurementInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateGroupProcurementInformationCompleted(this, new UpdateGroupProcurementInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/CreateGroupProcurementC" +
            "ontract", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateGroupProcurementContract(string systemcode, string CRVSerialNo, GProcurementContract gpc) {
            object[] results = this.Invoke("CreateGroupProcurementContract", new object[] {
                        systemcode,
                        CRVSerialNo,
                        gpc});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateGroupProcurementContractAsync(string systemcode, string CRVSerialNo, GProcurementContract gpc) {
            this.CreateGroupProcurementContractAsync(systemcode, CRVSerialNo, gpc, null);
        }
        
        /// <remarks/>
        public void CreateGroupProcurementContractAsync(string systemcode, string CRVSerialNo, GProcurementContract gpc, object userState) {
            if ((this.CreateGroupProcurementContractOperationCompleted == null)) {
                this.CreateGroupProcurementContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateGroupProcurementContractOperationCompleted);
            }
            this.InvokeAsync("CreateGroupProcurementContract", new object[] {
                        systemcode,
                        CRVSerialNo,
                        gpc}, this.CreateGroupProcurementContractOperationCompleted, userState);
        }
        
        private void OnCreateGroupProcurementContractOperationCompleted(object arg) {
            if ((this.CreateGroupProcurementContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateGroupProcurementContractCompleted(this, new CreateGroupProcurementContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crv.dc.capitaland.com/crvservice/TenderService.asm/UpdateGroupProcurementC" +
            "ontract", RequestNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", ResponseNamespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateGroupProcurementContract(string systemcode, string CRVSerialNo, GProcurementContract gpc) {
            object[] results = this.Invoke("UpdateGroupProcurementContract", new object[] {
                        systemcode,
                        CRVSerialNo,
                        gpc});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateGroupProcurementContractAsync(string systemcode, string CRVSerialNo, GProcurementContract gpc) {
            this.UpdateGroupProcurementContractAsync(systemcode, CRVSerialNo, gpc, null);
        }
        
        /// <remarks/>
        public void UpdateGroupProcurementContractAsync(string systemcode, string CRVSerialNo, GProcurementContract gpc, object userState) {
            if ((this.UpdateGroupProcurementContractOperationCompleted == null)) {
                this.UpdateGroupProcurementContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateGroupProcurementContractOperationCompleted);
            }
            this.InvokeAsync("UpdateGroupProcurementContract", new object[] {
                        systemcode,
                        CRVSerialNo,
                        gpc}, this.UpdateGroupProcurementContractOperationCompleted, userState);
        }
        
        private void OnUpdateGroupProcurementContractOperationCompleted(object arg) {
            if ((this.UpdateGroupProcurementContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateGroupProcurementContractCompleted(this, new UpdateGroupProcurementContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm")]
    public partial class CRVTender {
        
        private string objectIDField;
        
        private string objectNumberField;
        
        private string modifiedDateTimeField;
        
        private System.Nullable<int> targetTypeField;
        
        private string departmentField;
        
        private string projectRefNoField;
        
        private string projectTitleField;
        
        private string projectDescriptionField;
        
        private string awardReasonField;
        
        private string noAwardReasonField;
        
        private string awardDateField;
        
        private string anticipatedAwardDateField;
        
        private System.Nullable<int> numberOfContractsField;
        
        private CRVTenderVendor[] cRVTenderVendorsField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string ObjectNumber {
            get {
                return this.objectNumberField;
            }
            set {
                this.objectNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedDateTime {
            get {
                return this.modifiedDateTimeField;
            }
            set {
                this.modifiedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TargetType {
            get {
                return this.targetTypeField;
            }
            set {
                this.targetTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectRefNo {
            get {
                return this.projectRefNoField;
            }
            set {
                this.projectRefNoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectTitle {
            get {
                return this.projectTitleField;
            }
            set {
                this.projectTitleField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectDescription {
            get {
                return this.projectDescriptionField;
            }
            set {
                this.projectDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string AwardReason {
            get {
                return this.awardReasonField;
            }
            set {
                this.awardReasonField = value;
            }
        }
        
        /// <remarks/>
        public string NoAwardReason {
            get {
                return this.noAwardReasonField;
            }
            set {
                this.noAwardReasonField = value;
            }
        }
        
        /// <remarks/>
        public string AwardDate {
            get {
                return this.awardDateField;
            }
            set {
                this.awardDateField = value;
            }
        }
        
        /// <remarks/>
        public string AnticipatedAwardDate {
            get {
                return this.anticipatedAwardDateField;
            }
            set {
                this.anticipatedAwardDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NumberOfContracts {
            get {
                return this.numberOfContractsField;
            }
            set {
                this.numberOfContractsField = value;
            }
        }
        
        /// <remarks/>
        public CRVTenderVendor[] CRVTenderVendors {
            get {
                return this.cRVTenderVendorsField;
            }
            set {
                this.cRVTenderVendorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm")]
    public partial class CRVTenderVendor {
        
        private string objectIDField;
        
        private string cRVVendorIDField;
        
        private string vendorBRNField;
        
        private System.Nullable<int> statusField;
        
        private string awardDateField;
        
        private string modifiedDateTimeField;
        
        private string reasonField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string CRVVendorID {
            get {
                return this.cRVVendorIDField;
            }
            set {
                this.cRVVendorIDField = value;
            }
        }
        
        /// <remarks/>
        public string VendorBRN {
            get {
                return this.vendorBRNField;
            }
            set {
                this.vendorBRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string AwardDate {
            get {
                return this.awardDateField;
            }
            set {
                this.awardDateField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedDateTime {
            get {
                return this.modifiedDateTimeField;
            }
            set {
                this.modifiedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm")]
    public partial class GProcurementContract {
        
        private string objectIDField;
        
        private string contractRefNoField;
        
        private string tradeTypeIDField;
        
        private string descriptionField;
        
        private string cRVVendorIDField;
        
        private string vendorBRNField;
        
        private System.Nullable<decimal> awardedAmountField;
        
        private string startDateField;
        
        private string endDateField;
        
        private System.Nullable<int> contractStatusField;
        
        private string modifiedDateTimeField;
        
        private System.Nullable<int> isTermContractField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string ContractRefNo {
            get {
                return this.contractRefNoField;
            }
            set {
                this.contractRefNoField = value;
            }
        }
        
        /// <remarks/>
        public string TradeTypeID {
            get {
                return this.tradeTypeIDField;
            }
            set {
                this.tradeTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string CRVVendorID {
            get {
                return this.cRVVendorIDField;
            }
            set {
                this.cRVVendorIDField = value;
            }
        }
        
        /// <remarks/>
        public string VendorBRN {
            get {
                return this.vendorBRNField;
            }
            set {
                this.vendorBRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AwardedAmount {
            get {
                return this.awardedAmountField;
            }
            set {
                this.awardedAmountField = value;
            }
        }
        
        /// <remarks/>
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ContractStatus {
            get {
                return this.contractStatusField;
            }
            set {
                this.contractStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedDateTime {
            get {
                return this.modifiedDateTimeField;
            }
            set {
                this.modifiedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IsTermContract {
            get {
                return this.isTermContractField;
            }
            set {
                this.isTermContractField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm")]
    public partial class GroupProcurementInformation {
        
        private string objectIDField;
        
        private string projectTitleField;
        
        private string projectRefNoField;
        
        private string projectDescriptionField;
        
        private System.Nullable<decimal> contractSumField;
        
        private string currencyField;
        
        private string remarkField;
        
        private string modifiedDateTimeField;
        
        private GProcurementContract[] gProcurementContractsField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectTitle {
            get {
                return this.projectTitleField;
            }
            set {
                this.projectTitleField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectRefNo {
            get {
                return this.projectRefNoField;
            }
            set {
                this.projectRefNoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectDescription {
            get {
                return this.projectDescriptionField;
            }
            set {
                this.projectDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ContractSum {
            get {
                return this.contractSumField;
            }
            set {
                this.contractSumField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedDateTime {
            get {
                return this.modifiedDateTimeField;
            }
            set {
                this.modifiedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public GProcurementContract[] GProcurementContracts {
            get {
                return this.gProcurementContractsField;
            }
            set {
                this.gProcurementContractsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm")]
    public partial class GProjectContract {
        
        private string objectIDField;
        
        private string contractRefNoField;
        
        private string tradeTypeIDField;
        
        private string descriptionField;
        
        private string architectNameField;
        
        private string cRVVendorIDField;
        
        private string vendorBRNField;
        
        private System.Nullable<decimal> awardedAmountField;
        
        private string startDateField;
        
        private string endDateField;
        
        private System.Nullable<int> contractStatusField;
        
        private string modifiedDateTimeField;
        
        private System.Nullable<int> isTermContractField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string ContractRefNo {
            get {
                return this.contractRefNoField;
            }
            set {
                this.contractRefNoField = value;
            }
        }
        
        /// <remarks/>
        public string TradeTypeID {
            get {
                return this.tradeTypeIDField;
            }
            set {
                this.tradeTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ArchitectName {
            get {
                return this.architectNameField;
            }
            set {
                this.architectNameField = value;
            }
        }
        
        /// <remarks/>
        public string CRVVendorID {
            get {
                return this.cRVVendorIDField;
            }
            set {
                this.cRVVendorIDField = value;
            }
        }
        
        /// <remarks/>
        public string VendorBRN {
            get {
                return this.vendorBRNField;
            }
            set {
                this.vendorBRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AwardedAmount {
            get {
                return this.awardedAmountField;
            }
            set {
                this.awardedAmountField = value;
            }
        }
        
        /// <remarks/>
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ContractStatus {
            get {
                return this.contractStatusField;
            }
            set {
                this.contractStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedDateTime {
            get {
                return this.modifiedDateTimeField;
            }
            set {
                this.modifiedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IsTermContract {
            get {
                return this.isTermContractField;
            }
            set {
                this.isTermContractField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://crv.dc.capitaland.com/crvservice/TenderService.asm")]
    public partial class GroupProjectInformation {
        
        private string objectIDField;
        
        private string projectTitleField;
        
        private string projectRefNoField;
        
        private string projectDescriptionField;
        
        private string countryField;
        
        private string cityField;
        
        private string currencyField;
        
        private string projectManagerField;
        
        private string remarkField;
        
        private System.Nullable<decimal> grossFloorAreaField;
        
        private System.Nullable<decimal> siteAreaField;
        
        private System.Nullable<decimal> constructionCostField;
        
        private System.Nullable<decimal> constructionFloorAreaField;
        
        private string modifiedDateTimeField;
        
        private GProjectContract[] gProjectContractsField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectTitle {
            get {
                return this.projectTitleField;
            }
            set {
                this.projectTitleField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectRefNo {
            get {
                return this.projectRefNoField;
            }
            set {
                this.projectRefNoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectDescription {
            get {
                return this.projectDescriptionField;
            }
            set {
                this.projectDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectManager {
            get {
                return this.projectManagerField;
            }
            set {
                this.projectManagerField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> GrossFloorArea {
            get {
                return this.grossFloorAreaField;
            }
            set {
                this.grossFloorAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SiteArea {
            get {
                return this.siteAreaField;
            }
            set {
                this.siteAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ConstructionCost {
            get {
                return this.constructionCostField;
            }
            set {
                this.constructionCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ConstructionFloorArea {
            get {
                return this.constructionFloorAreaField;
            }
            set {
                this.constructionFloorAreaField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedDateTime {
            get {
                return this.modifiedDateTimeField;
            }
            set {
                this.modifiedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public GProjectContract[] GProjectContracts {
            get {
                return this.gProjectContractsField;
            }
            set {
                this.gProjectContractsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetActiveCRVSerialNumbersCompletedEventHandler(object sender, GetActiveCRVSerialNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveCRVSerialNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveCRVSerialNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ConfirmCRVSerialUsageCompletedEventHandler(object sender, ConfirmCRVSerialUsageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmCRVSerialUsageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmCRVSerialUsageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UpdateTenderProjectRefNoCompletedEventHandler(object sender, UpdateTenderProjectRefNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTenderProjectRefNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTenderProjectRefNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetFullTenderInfoCompletedEventHandler(object sender, GetFullTenderInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFullTenderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFullTenderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CRVTender Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CRVTender)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetTenderNoOfContractsCompletedEventHandler(object sender, GetTenderNoOfContractsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTenderNoOfContractsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTenderNoOfContractsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Nullable<int> Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<int>)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CloseTenderCompletedEventHandler(object sender, CloseTenderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloseTenderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CloseTenderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Nullable<int> Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<int>)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CancelTenderCompletedEventHandler(object sender, CancelTenderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelTenderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelTenderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Nullable<int> Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<int>)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UpdateTenderVendorAwardStatusCompletedEventHandler(object sender, UpdateTenderVendorAwardStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTenderVendorAwardStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTenderVendorAwardStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetGroupProjectInformationCompletedEventHandler(object sender, GetGroupProjectInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupProjectInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupProjectInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GroupProjectInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GroupProjectInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UpdateGroupProjectInformationCompletedEventHandler(object sender, UpdateGroupProjectInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateGroupProjectInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateGroupProjectInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CreateGroupProjectContractCompletedEventHandler(object sender, CreateGroupProjectContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateGroupProjectContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateGroupProjectContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UpdateGroupProjectContractCompletedEventHandler(object sender, UpdateGroupProjectContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateGroupProjectContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateGroupProjectContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetGroupProcurementInformationCompletedEventHandler(object sender, GetGroupProcurementInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupProcurementInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupProcurementInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GroupProcurementInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GroupProcurementInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UpdateGroupProcurementInformationCompletedEventHandler(object sender, UpdateGroupProcurementInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateGroupProcurementInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateGroupProcurementInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CreateGroupProcurementContractCompletedEventHandler(object sender, CreateGroupProcurementContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateGroupProcurementContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateGroupProcurementContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UpdateGroupProcurementContractCompletedEventHandler(object sender, UpdateGroupProcurementContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateGroupProcurementContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateGroupProcurementContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591