//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicLayer.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is insufficient amount in the budget for adjustment of the following accounts: {0}.
        /// </summary>
        internal static string BudgetAdjustment_InsufficientAmount {
            get {
                return ResourceManager.GetString("BudgetAdjustment_InsufficientAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to submit for
        /// approval because you are reallocating budget to {0}
        ///but reallocating any budget not from {0}..
        /// </summary>
        internal static string BudgetReallocation_budgetFromLess {
            get {
                return ResourceManager.GetString("BudgetReallocation_budgetFromLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to submit for
        /// approval because the reallocating budget {0} has error in amount
        ///.
        /// </summary>
        internal static string BudgetReallocation_budgetFromNotMatchTo {
            get {
                return ResourceManager.GetString("BudgetReallocation_budgetFromNotMatchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to submit for approval because you are 
        ///reallocating budget from {0}  
        ///but reallocating any budget not to {0}..
        /// </summary>
        internal static string BudgetReallocation_budgetToLess {
            get {
                return ResourceManager.GetString("BudgetReallocation_budgetToLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is insufficient amount in the source budget for adjustment of the following accounts: {0}.
        /// </summary>
        internal static string BudgetReallocation_InsufficientAmount {
            get {
                return ResourceManager.GetString("BudgetReallocation_InsufficientAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRV serial number confirm usage unsuccessful. Please Use another CRV serial number..
        /// </summary>
        internal static string CRVSerialNumberConfirmUsageUnsuccessful {
            get {
                return ResourceManager.GetString("CRVSerialNumberConfirmUsageUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRV tender service connection fail..
        /// </summary>
        internal static string CRVTenderService_ConnectionFail {
            get {
                return ResourceManager.GetString("CRVTenderService_ConnectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Code not found for selected location..
        /// </summary>
        internal static string CRVTenderService_SystemCodeNotFound {
            get {
                return ResourceManager.GetString("CRVTenderService_SystemCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message cannot be sent because the message template with the code &apos;{0}&apos; cannot be found..
        /// </summary>
        internal static string MessageTemplate_MessageTemplateCannotBeFound {
            get {
                return ResourceManager.GetString("MessageTemplate_MessageTemplateCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to transfer amount of ({0:#,##0.00}) from the previous purchase document..
        /// </summary>
        internal static string PurchaseBudget_UnableToTransferAmountFromTransactionLog {
            get {
                return ResourceManager.GetString("PurchaseBudget_UnableToTransferAmountFromTransactionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update CRV Tender Vendor Award Status Fail.
        /// </summary>
        internal static string RequestForQuotation_UpdateCRVTenderVendorAwardStatusFail {
            get {
                return ResourceManager.GetString("RequestForQuotation_UpdateCRVTenderVendorAwardStatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check out item {0} because it is already checked out. Please uncheck the item..
        /// </summary>
        internal static string Work_ItemAlreadyCheckOut {
            get {
                return ResourceManager.GetString("Work_ItemAlreadyCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to assign task to approvers because the Approval Process Detail is not specified, or has been deleted. This can happen if you configured the workflow to execute the SetStateAndAssignApprovers activity, but did not specify SubmitForApproval in the previous EventDriven activity..
        /// </summary>
        internal static string Workflow_ApprovalProcessDetailNotSpecified {
            get {
                return ResourceManager.GetString("Workflow_ApprovalProcessDetailNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to assign users to the workflow task because the list returns by the workflow contains objects that are not of the OUser type..
        /// </summary>
        internal static string Workflow_ListInvalid {
            get {
                return ResourceManager.GetString("Workflow_ListInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to trigger workflow event because the Activity for this PersistentObject &apos;{0}&apos; (ObjectID={1}) because there is no workflow instance ID. Did you forget to create this object with the IWorkflowEnabled interface?.
        /// </summary>
        internal static string Workflow_NoWorkflowInstanceID {
            get {
                return ResourceManager.GetString("Workflow_NoWorkflowInstanceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow engine is unable to assign any approvers to the workflow task. This may be because the positions, approval hierarchies and approval processes have not been correctly configured..
        /// </summary>
        internal static string Workflow_UnableToAssignApprovers {
            get {
                return ResourceManager.GetString("Workflow_UnableToAssignApprovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow engine is unable to assign any users or positions to the workflow task..
        /// </summary>
        internal static string Workflow_UnableToAssignUsersOrPositions {
            get {
                return ResourceManager.GetString("Workflow_UnableToAssignUsersOrPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow engine is unable to allow you to approve this task. This happens because the mode of forwarding for the approval process is &quot;All&quot; and because you are not an authorized user set up in the approval hierarchy..
        /// </summary>
        internal static string Workflow_UnauthorizedApproverException {
            get {
                return ResourceManager.GetString("Workflow_UnauthorizedApproverException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to trigger workflow event because the Activity for this PersistentObject &apos;{0}&apos; (ObjectID={1}) has not been created. Did you forget to create this object with the IWorkflowEnabled interface?.
        /// </summary>
        internal static string Workflow_WorkflowNotCreated {
            get {
                return ResourceManager.GetString("Workflow_WorkflowNotCreated", resourceCulture);
            }
        }
    }
}
