//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Objects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Objects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicLayer.Resources.Objects", typeof(Objects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string CenterAdmin {
            get {
                return ResourceManager.GetString("CenterAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string CenterAnalysis {
            get {
                return ResourceManager.GetString("CenterAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        internal static string CenterAsset {
            get {
                return ResourceManager.GetString("CenterAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string CenterBudget {
            get {
                return ResourceManager.GetString("CenterBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string CenterInventory {
            get {
                return ResourceManager.GetString("CenterInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement.
        /// </summary>
        internal static string CenterProcurement {
            get {
                return ResourceManager.GetString("CenterProcurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Builder.
        /// </summary>
        internal static string CenterReportBuilder {
            get {
                return ResourceManager.GetString("CenterReportBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string CenterService {
            get {
                return ResourceManager.GetString("CenterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string CenterVendor {
            get {
                return ResourceManager.GetString("CenterVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string CenterWork {
            get {
                return ResourceManager.GetString("CenterWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string MiscDatabase {
            get {
                return ResourceManager.GetString("MiscDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Created Cases.
        /// </summary>
        internal static string MiscMyCreatedCases {
            get {
                return ResourceManager.GetString("MiscMyCreatedCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Created Cases.
        /// </summary>
        internal static string MiscMyWork {
            get {
                return ResourceManager.GetString("MiscMyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign Tasks.
        /// </summary>
        internal static string MiscReassignTasks {
            get {
                return ResourceManager.GetString("MiscReassignTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate Report.
        /// </summary>
        internal static string MiscReportMigrate {
            get {
                return ResourceManager.GetString("MiscReportMigrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string OAccount {
            get {
                return ResourceManager.GetString("OAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACG Data.
        /// </summary>
        internal static string OACGData {
            get {
                return ResourceManager.GetString("OACGData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement.
        /// </summary>
        internal static string OAnnouncement {
            get {
                return ResourceManager.GetString("OAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Setting.
        /// </summary>
        internal static string OApplicationSetting {
            get {
                return ResourceManager.GetString("OApplicationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Hierarchy.
        /// </summary>
        internal static string OApprovalHierarchy {
            get {
                return ResourceManager.GetString("OApprovalHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Process.
        /// </summary>
        internal static string OApprovalProcess {
            get {
                return ResourceManager.GetString("OApprovalProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Type.
        /// </summary>
        internal static string OAttachmentType {
            get {
                return ResourceManager.GetString("OAttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trail.
        /// </summary>
        internal static string OAuditTrail {
            get {
                return ResourceManager.GetString("OAuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trail (Database Fields).
        /// </summary>
        internal static string OAuditTrailField {
            get {
                return ResourceManager.GetString("OAuditTrailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMS Transmission Status.
        /// </summary>
        internal static string OBMSTransmissionStatus {
            get {
                return ResourceManager.GetString("OBMSTransmissionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string OBudget {
            get {
                return ResourceManager.GetString("OBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Adjustment.
        /// </summary>
        internal static string OBudgetAdjustment {
            get {
                return ResourceManager.GetString("OBudgetAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Group.
        /// </summary>
        internal static string OBudgetGroup {
            get {
                return ResourceManager.GetString("OBudgetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Period.
        /// </summary>
        internal static string OBudgetPeriod {
            get {
                return ResourceManager.GetString("OBudgetPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Reallocation.
        /// </summary>
        internal static string OBudgetReallocation {
            get {
                return ResourceManager.GetString("OBudgetReallocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string OCalendar {
            get {
                return ResourceManager.GetString("OCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        internal static string OCampaign {
            get {
                return ResourceManager.GetString("OCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string OCapitalandCompany {
            get {
                return ResourceManager.GetString("OCapitalandCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        internal static string OCase {
            get {
                return ResourceManager.GetString("OCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Catalog.
        /// </summary>
        internal static string OCatalogue {
            get {
                return ResourceManager.GetString("OCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist.
        /// </summary>
        internal static string OChecklist {
            get {
                return ResourceManager.GetString("OChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist Response.
        /// </summary>
        internal static string OChecklistResponse {
            get {
                return ResourceManager.GetString("OChecklistResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string OCode {
            get {
                return ResourceManager.GetString("OCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Type.
        /// </summary>
        internal static string OCodeType {
            get {
                return ResourceManager.GetString("OCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string OCompany {
            get {
                return ResourceManager.GetString("OCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string OContract {
            get {
                return ResourceManager.GetString("OContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafts.
        /// </summary>
        internal static string OCraft {
            get {
                return ResourceManager.GetString("OCraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string OCurrency {
            get {
                return ResourceManager.GetString("OCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Exchange Rate.
        /// </summary>
        internal static string OCurrencyExchange {
            get {
                return ResourceManager.GetString("OCurrencyExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized Object.
        /// </summary>
        internal static string OCustomizedObject {
            get {
                return ResourceManager.GetString("OCustomizedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized Object.
        /// </summary>
        internal static string OCustomizedRecordObject {
            get {
                return ResourceManager.GetString("OCustomizedRecordObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string ODashboard {
            get {
                return ResourceManager.GetString("ODashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Template.
        /// </summary>
        internal static string ODocumentTemplate {
            get {
                return ResourceManager.GetString("ODocumentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Template Type.
        /// </summary>
        internal static string ODocumentTemplateType {
            get {
                return ResourceManager.GetString("ODocumentTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Email History.
        /// </summary>
        internal static string OEmailLog {
            get {
                return ResourceManager.GetString("OEmailLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string OEquipment {
            get {
                return ResourceManager.GetString("OEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Type.
        /// </summary>
        internal static string OEquipmentType {
            get {
                return ResourceManager.GetString("OEquipmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Write-Off.
        /// </summary>
        internal static string OEquipmentWriteOff {
            get {
                return ResourceManager.GetString("OEquipmentWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Catalog.
        /// </summary>
        internal static string OFixedRate {
            get {
                return ResourceManager.GetString("OFixedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string OFunction {
            get {
                return ResourceManager.GetString("OFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string OLanguage {
            get {
                return ResourceManager.GetString("OLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string OLocation {
            get {
                return ResourceManager.GetString("OLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Type.
        /// </summary>
        internal static string OLocationType {
            get {
                return ResourceManager.GetString("OLocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message History.
        /// </summary>
        internal static string OMessage {
            get {
                return ResourceManager.GetString("OMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Template.
        /// </summary>
        internal static string OMessageTemplate {
            get {
                return ResourceManager.GetString("OMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        internal static string OMeter {
            get {
                return ResourceManager.GetString("OMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Hierarchy.
        /// </summary>
        internal static string ONotificationHierarchy {
            get {
                return ResourceManager.GetString("ONotificationHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Milestones.
        /// </summary>
        internal static string ONotificationMilestones {
            get {
                return ResourceManager.GetString("ONotificationMilestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Process.
        /// </summary>
        internal static string ONotificationProcess {
            get {
                return ResourceManager.GetString("ONotificationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC AE Event.
        /// </summary>
        internal static string OOPCAEEvent {
            get {
                return ResourceManager.GetString("OOPCAEEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC AE Server.
        /// </summary>
        internal static string OOPCAEServer {
            get {
                return ResourceManager.GetString("OOPCAEServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC DA Server.
        /// </summary>
        internal static string OOPCDAServer {
            get {
                return ResourceManager.GetString("OOPCDAServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string OPoint {
            get {
                return ResourceManager.GetString("OPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Tariffs and Discounts.
        /// </summary>
        internal static string OPointTariff {
            get {
                return ResourceManager.GetString("OPointTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Template.
        /// </summary>
        internal static string OPointTrigger {
            get {
                return ResourceManager.GetString("OPointTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string OPosition {
            get {
                return ResourceManager.GetString("OPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoice.
        /// </summary>
        internal static string OPurchaseInvoice {
            get {
                return ResourceManager.GetString("OPurchaseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO / LOA.
        /// </summary>
        internal static string OPurchaseOrder {
            get {
                return ResourceManager.GetString("OPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Request.
        /// </summary>
        internal static string OPurchaseRequest {
            get {
                return ResourceManager.GetString("OPurchaseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Settings.
        /// </summary>
        internal static string OPurchaseSettings {
            get {
                return ResourceManager.GetString("OPurchaseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        internal static string OReading {
            get {
                return ResourceManager.GetString("OReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill To AMOS.
        /// </summary>
        internal static string OReading_BillToAMOS {
            get {
                return ResourceManager.GetString("OReading_BillToAMOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading (Multiple).
        /// </summary>
        internal static string OReading_Multiple {
            get {
                return ResourceManager.GetString("OReading_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string OReport {
            get {
                return ResourceManager.GetString("OReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Justification.
        /// </summary>
        internal static string ORequestForQuotation {
            get {
                return ResourceManager.GetString("ORequestForQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string ORole {
            get {
                return ResourceManager.GetString("ORole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Number Generator.
        /// </summary>
        internal static string ORunningNumberGenerator {
            get {
                return ResourceManager.GetString("ORunningNumberGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Precaution.
        /// </summary>
        internal static string OSafetyPrecaution {
            get {
                return ResourceManager.GetString("OSafetyPrecaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Work.
        /// </summary>
        internal static string OScheduledWork {
            get {
                return ResourceManager.GetString("OScheduledWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Level.
        /// </summary>
        internal static string OServiceLevel {
            get {
                return ResourceManager.GetString("OServiceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login History.
        /// </summary>
        internal static string OSessionAudit {
            get {
                return ResourceManager.GetString("OSessionAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string OShift {
            get {
                return ResourceManager.GetString("OShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string OStore {
            get {
                return ResourceManager.GetString("OStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        internal static string OStoreAdjust {
            get {
                return ResourceManager.GetString("OStoreAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In.
        /// </summary>
        internal static string OStoreCheckIn {
            get {
                return ResourceManager.GetString("OStoreCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Out.
        /// </summary>
        internal static string OStoreCheckOut {
            get {
                return ResourceManager.GetString("OStoreCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string OStoreRequest {
            get {
                return ResourceManager.GetString("OStoreRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock View.
        /// </summary>
        internal static string OStoreStock {
            get {
                return ResourceManager.GetString("OStoreStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Take.
        /// </summary>
        internal static string OStoreStockTake {
            get {
                return ResourceManager.GetString("OStoreStockTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string OStoreTransfer {
            get {
                return ResourceManager.GetString("OStoreTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Group.
        /// </summary>
        internal static string OSurveyGroup {
            get {
                return ResourceManager.GetString("OSurveyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Planner.
        /// </summary>
        internal static string OSurveyPlanner {
            get {
                return ResourceManager.GetString("OSurveyPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Respondent.
        /// </summary>
        internal static string OSurveyRespondent {
            get {
                return ResourceManager.GetString("OSurveyRespondent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        internal static string OTaxCode {
            get {
                return ResourceManager.GetString("OTaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician Roster.
        /// </summary>
        internal static string OTechnicianRoster {
            get {
                return ResourceManager.GetString("OTechnicianRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        internal static string OTenant {
            get {
                return ResourceManager.GetString("OTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Activity.
        /// </summary>
        internal static string OTenantActivity {
            get {
                return ResourceManager.GetString("OTenantActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Contact.
        /// </summary>
        internal static string OTenantContact {
            get {
                return ResourceManager.GetString("OTenantContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Lease.
        /// </summary>
        internal static string OTenantLease {
            get {
                return ResourceManager.GetString("OTenantLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Conversion.
        /// </summary>
        internal static string OUnitConversion {
            get {
                return ResourceManager.GetString("OUnitConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string OUser {
            get {
                return ResourceManager.GetString("OUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Creation.
        /// </summary>
        internal static string OUserCreation {
            get {
                return ResourceManager.GetString("OUserCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Update.
        /// </summary>
        internal static string OUserUpdate {
            get {
                return ResourceManager.GetString("OUserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        internal static string OUtility {
            get {
                return ResourceManager.GetString("OUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string OVendor {
            get {
                return ResourceManager.GetString("OVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Prequalification.
        /// </summary>
        internal static string OVendorPrequalification {
            get {
                return ResourceManager.GetString("OVendorPrequalification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string OWork {
            get {
                return ResourceManager.GetString("OWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Repository.
        /// </summary>
        internal static string OWorkflowRepository {
            get {
                return ResourceManager.GetString("OWorkflowRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAM Services.
        /// </summary>
        internal static string ServiceView {
            get {
                return ResourceManager.GetString("ServiceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trails.
        /// </summary>
        internal static string SubCategoryAuditTrail {
            get {
                return ResourceManager.GetString("SubCategoryAuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes.
        /// </summary>
        internal static string SubCategoryCodes {
            get {
                return ResourceManager.GetString("SubCategoryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Administration.
        /// </summary>
        internal static string SubCategoryGeneralAdmin {
            get {
                return ResourceManager.GetString("SubCategoryGeneralAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard/Report Builder.
        /// </summary>
        internal static string SubCategoryReportBuilder {
            get {
                return ResourceManager.GetString("SubCategoryReportBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Administration.
        /// </summary>
        internal static string SubCategorySystemAdmin {
            get {
                return ResourceManager.GetString("SubCategorySystemAdmin", resourceCulture);
            }
        }
    }
}
