//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicLayer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Account_Group {
            get {
                return ResourceManager.GetString("Account_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Item.
        /// </summary>
        internal static string Account_LineItem {
            get {
                return ResourceManager.GetString("Account_LineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Posted (Cancelled).
        /// </summary>
        internal static string BillToAMOSStatusText_NotPostedCancelled {
            get {
                return ResourceManager.GetString("BillToAMOSStatusText_NotPostedCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Posted to AMOS.
        /// </summary>
        internal static string BillToAMOSStatusText_NotPostedToAmos {
            get {
                return ResourceManager.GetString("BillToAMOSStatusText_NotPostedToAmos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Posting to AMOS.
        /// </summary>
        internal static string BillToAMOSStatusText_PendingPosting {
            get {
                return ResourceManager.GetString("BillToAMOSStatusText_PendingPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted To AMOS (Waiting for AMOS to process).
        /// </summary>
        internal static string BillToAMOSStatusText_PostedToAmos {
            get {
                return ResourceManager.GetString("BillToAMOSStatusText_PostedToAmos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted to AMOS (FAILED).
        /// </summary>
        internal static string BillToAMOSStatusText_PostedToAmosFailed {
            get {
                return ResourceManager.GetString("BillToAMOSStatusText_PostedToAmosFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted to AMOS (SUCCESSFUL).
        /// </summary>
        internal static string BillToAMOSStatusText_PostedToAmosSuccessful {
            get {
                return ResourceManager.GetString("BillToAMOSStatusText_PostedToAmosSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to post to AMOS due to error.
        /// </summary>
        internal static string BillToAMOSStatusText_UnableToPostDueToError {
            get {
                return ResourceManager.GetString("BillToAMOSStatusText_UnableToPostDueToError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire.
        /// </summary>
        internal static string BudgetDistributionMode_Entire {
            get {
                return ResourceManager.GetString("BudgetDistributionMode_Entire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Items.
        /// </summary>
        internal static string BudgetDistributionMode_LineItems {
            get {
                return ResourceManager.GetString("BudgetDistributionMode_LineItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following budget items do not have enough available amount to be revised : .
        /// </summary>
        internal static string BudgetReadjustment_InsufficientItem {
            get {
                return ResourceManager.GetString("BudgetReadjustment_InsufficientItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following budget items do not have enough available amount to be transferred: .
        /// </summary>
        internal static string BudgetReallocation_InsufficientItem {
            get {
                return ResourceManager.GetString("BudgetReallocation_InsufficientItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget = Line Items.
        /// </summary>
        internal static string BudgetValidationPolicy_BudgetConsumptionEqualsItems {
            get {
                return ResourceManager.GetString("BudgetValidationPolicy_BudgetConsumptionEqualsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget &lt;= Line Items.
        /// </summary>
        internal static string BudgetValidationPolicy_BudgetConsumptionLessThanItems {
            get {
                return ResourceManager.GetString("BudgetValidationPolicy_BudgetConsumptionLessThanItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Not Required.
        /// </summary>
        internal static string BudgetValidationPolicy_NotRequired {
            get {
                return ResourceManager.GetString("BudgetValidationPolicy_NotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        internal static string CheckItemType_Choice {
            get {
                return ResourceManager.GetString("CheckItemType_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CheckItemType_None {
            get {
                return ResourceManager.GetString("CheckItemType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string CheckItemType_Remarks {
            get {
                return ResourceManager.GetString("CheckItemType_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Costing.
        /// </summary>
        internal static string CostingType_AverageCosting {
            get {
                return ResourceManager.GetString("CostingType_AverageCosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry.
        /// </summary>
        internal static string CostingType_Expiry {
            get {
                return ResourceManager.GetString("CostingType_Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFO.
        /// </summary>
        internal static string CostingType_FIFO {
            get {
                return ResourceManager.GetString("CostingType_FIFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIFO.
        /// </summary>
        internal static string CostingType_LIFO {
            get {
                return ResourceManager.GetString("CostingType_LIFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Costing.
        /// </summary>
        internal static string CostingType_StandardCosting {
            get {
                return ResourceManager.GetString("CostingType_StandardCosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string CostType_AdhocRate {
            get {
                return ResourceManager.GetString("CostType_AdhocRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Rate.
        /// </summary>
        internal static string CostType_FixedRate {
            get {
                return ResourceManager.GetString("CostType_FixedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string CostType_Material {
            get {
                return ResourceManager.GetString("CostType_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string CostType_TaxCode {
            get {
                return ResourceManager.GetString("CostType_TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        internal static string CostType_Technician {
            get {
                return ResourceManager.GetString("CostType_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string DashboardType_Basic {
            get {
                return ResourceManager.GetString("DashboardType_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubble.
        /// </summary>
        internal static string DashboardType_Bubble {
            get {
                return ResourceManager.GetString("DashboardType_Bubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauge.
        /// </summary>
        internal static string DashboardType_Gauge {
            get {
                return ResourceManager.GetString("DashboardType_Gauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        internal static string DashboardType_Grid {
            get {
                return ResourceManager.GetString("DashboardType_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie.
        /// </summary>
        internal static string DashboardType_Pie {
            get {
                return ResourceManager.GetString("DashboardType_Pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polar.
        /// </summary>
        internal static string DashboardType_Polar {
            get {
                return ResourceManager.GetString("DashboardType_Polar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar.
        /// </summary>
        internal static string DashboardType_Radar {
            get {
                return ResourceManager.GetString("DashboardType_Radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter.
        /// </summary>
        internal static string DashboardType_Scatter {
            get {
                return ResourceManager.GetString("DashboardType_Scatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrobat PDF.
        /// </summary>
        internal static string Document_Acrobat {
            get {
                return ResourceManager.GetString("Document_Acrobat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel.
        /// </summary>
        internal static string Document_Excel {
            get {
                return ResourceManager.GetString("Document_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpeg Image.
        /// </summary>
        internal static string Document_Image {
            get {
                return ResourceManager.GetString("Document_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Page.
        /// </summary>
        internal static string Document_Static {
            get {
                return ResourceManager.GetString("Document_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word.
        /// </summary>
        internal static string Document_Word {
            get {
                return ResourceManager.GetString("Document_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Pending.
        /// </summary>
        internal static string EAMservice_ContinuePending {
            get {
                return ResourceManager.GetString("EAMservice_ContinuePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string EAMservice_Paused {
            get {
                return ResourceManager.GetString("EAMservice_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Pending.
        /// </summary>
        internal static string EAMservice_PausePending {
            get {
                return ResourceManager.GetString("EAMservice_PausePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string EAMservice_Running {
            get {
                return ResourceManager.GetString("EAMservice_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Pending.
        /// </summary>
        internal static string EAMservice_StartPending {
            get {
                return ResourceManager.GetString("EAMservice_StartPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string EAMservice_Stop {
            get {
                return ResourceManager.GetString("EAMservice_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Pending.
        /// </summary>
        internal static string EAMservice_StopPending {
            get {
                return ResourceManager.GetString("EAMservice_StopPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save equipment as the default unit of measure is not defined in the application settings..
        /// </summary>
        internal static string Equipment_UnitOfMeasureNotDefined {
            get {
                return ResourceManager.GetString("Equipment_UnitOfMeasureNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string EquipmentStatus_Active {
            get {
                return ResourceManager.GetString("EquipmentStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string EquipmentStatus_Confirmed {
            get {
                return ResourceManager.GetString("EquipmentStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaged.
        /// </summary>
        internal static string EquipmentStatus_Damaged {
            get {
                return ResourceManager.GetString("EquipmentStatus_Damaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Repair.
        /// </summary>
        internal static string EquipmentStatus_InRepair {
            get {
                return ResourceManager.GetString("EquipmentStatus_InRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Acceptance.
        /// </summary>
        internal static string EquipmentStatus_PendingAcceptance {
            get {
                return ResourceManager.GetString("EquipmentStatus_PendingAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Write Off.
        /// </summary>
        internal static string EquipmentStatus_PendingWriteOff {
            get {
                return ResourceManager.GetString("EquipmentStatus_PendingWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retired.
        /// </summary>
        internal static string EquipmentStatus_Retired {
            get {
                return ResourceManager.GetString("EquipmentStatus_Retired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written Off.
        /// </summary>
        internal static string EquipmentStatus_WrittenOff {
            get {
                return ResourceManager.GetString("EquipmentStatus_WrittenOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.A..
        /// </summary>
        internal static string General_NA {
            get {
                return ResourceManager.GetString("General_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string General_No {
            get {
                return ResourceManager.GetString("General_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string General_Yes {
            get {
                return ResourceManager.GetString("General_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumable.
        /// </summary>
        internal static string InventoryCatalogType_Consumable {
            get {
                return ResourceManager.GetString("InventoryCatalogType_Consumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string InventoryCatalogType_Equipment {
            get {
                return ResourceManager.GetString("InventoryCatalogType_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Consumable.
        /// </summary>
        internal static string InventoryCatalogType_NonConsumable {
            get {
                return ResourceManager.GetString("InventoryCatalogType_NonConsumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Memo.
        /// </summary>
        internal static string InvoiceType_CreditMemo {
            get {
                return ResourceManager.GetString("InvoiceType_CreditMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Memo.
        /// </summary>
        internal static string InvoiceType_DebitMemo {
            get {
                return ResourceManager.GetString("InvoiceType_DebitMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Expense.
        /// </summary>
        internal static string InvoiceType_DirectExpense {
            get {
                return ResourceManager.GetString("InvoiceType_DirectExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Invoice.
        /// </summary>
        internal static string InvoiceType_StandardInvoice {
            get {
                return ResourceManager.GetString("InvoiceType_StandardInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Stocked.
        /// </summary>
        internal static string ItemType_NonStocked {
            get {
                return ResourceManager.GetString("ItemType_NonStocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Order.
        /// </summary>
        internal static string ItemType_SpecialOrder {
            get {
                return ResourceManager.GetString("ItemType_SpecialOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocked.
        /// </summary>
        internal static string ItemType_Stocked {
            get {
                return ResourceManager.GetString("ItemType_Stocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string LocationStockTakeItemType_Equipment {
            get {
                return ResourceManager.GetString("LocationStockTakeItemType_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonConsumable.
        /// </summary>
        internal static string LocationStockTakeItemType_NonConsumable {
            get {
                return ResourceManager.GetString("LocationStockTakeItemType_NonConsumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Invoice.
        /// </summary>
        internal static string MatchType_DirectInvoice {
            get {
                return ResourceManager.GetString("MatchType_DirectInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO-Matched Invoice .
        /// </summary>
        internal static string MatchType_InvoiceMatchedToPO {
            get {
                return ResourceManager.GetString("MatchType_InvoiceMatchedToPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO-Receipt-Matched Invoice.
        /// </summary>
        internal static string MatchType_InvoiceMatchedToPOReceipt {
            get {
                return ResourceManager.GetString("MatchType_InvoiceMatchedToPOReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;THE FOLLOWING MESSAGE IS COPIED TO YOU FOR INFORMATION.&lt;/b&gt;&lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        internal static string Message_CarbonCopyBodyPrefix {
            get {
                return ResourceManager.GetString("Message_CarbonCopyBodyPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon-Copy: .
        /// </summary>
        internal static string Message_CarbonCopySubjectPrefix {
            get {
                return ResourceManager.GetString("Message_CarbonCopySubjectPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Required.
        /// </summary>
        internal static string MinimumNumberOfQuotations_NotRequired {
            get {
                return ResourceManager.GetString("MinimumNumberOfQuotations_NotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred.
        /// </summary>
        internal static string MinimumNumberOfQuotations_Preferred {
            get {
                return ResourceManager.GetString("MinimumNumberOfQuotations_Preferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string MinimumNumberOfQuotations_Required {
            get {
                return ResourceManager.GetString("MinimumNumberOfQuotations_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ModeOfForwarding_All {
            get {
                return ResourceManager.GetString("ModeOfForwarding_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        internal static string ModeOfForwarding_Direct {
            get {
                return ResourceManager.GetString("ModeOfForwarding_Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchical.
        /// </summary>
        internal static string ModeOfForwarding_Hierarchical {
            get {
                return ResourceManager.GetString("ModeOfForwarding_Hierarchical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchical (with Last Rejected and Next Required Approval Skipping).
        /// </summary>
        internal static string ModeOfForwarding_HierarchicalWithLastRejectedAndNextRequiredApprovalSkipping {
            get {
                return ResourceManager.GetString("ModeOfForwarding_HierarchicalWithLastRejectedAndNextRequiredApprovalSkipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchical (with Last Rejected Skipping).
        /// </summary>
        internal static string ModeOfForwarding_HierarchicalWithLastRejectedSkipping {
            get {
                return ResourceManager.GetString("ModeOfForwarding_HierarchicalWithLastRejectedSkipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ModeOfForwarding_None {
            get {
                return ResourceManager.GetString("ModeOfForwarding_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO_SUBSCRIPTION_FOUND.
        /// </summary>
        internal static string NO_SUBSCRIPTION_FOUND {
            get {
                return ResourceManager.GetString("NO_SUBSCRIPTION_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute.
        /// </summary>
        internal static string Point_AbsoluteMeter {
            get {
                return ResourceManager.GetString("Point_AbsoluteMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string Point_Equipment {
            get {
                return ResourceManager.GetString("Point_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increasing.
        /// </summary>
        internal static string Point_IncreasingMeter {
            get {
                return ResourceManager.GetString("Point_IncreasingMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Point_Location {
            get {
                return ResourceManager.GetString("Point_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one.
        /// </summary>
        internal static string Position_NoOne {
            get {
                return ResourceManager.GetString("Position_NoOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 (Low).
        /// </summary>
        internal static string Priority_0 {
            get {
                return ResourceManager.GetString("Priority_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 (Medium).
        /// </summary>
        internal static string Priority_1 {
            get {
                return ResourceManager.GetString("Priority_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 (High).
        /// </summary>
        internal static string Priority_2 {
            get {
                return ResourceManager.GetString("Priority_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 (Critical).
        /// </summary>
        internal static string Priority_3 {
            get {
                return ResourceManager.GetString("Priority_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string PurchaseItemType_Contract {
            get {
                return ResourceManager.GetString("PurchaseItemType_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string PurchaseItemType_Material {
            get {
                return ResourceManager.GetString("PurchaseItemType_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string PurchaseItemType_Others {
            get {
                return ResourceManager.GetString("PurchaseItemType_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string PurchaseItemType_Service {
            get {
                return ResourceManager.GetString("PurchaseItemType_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 {0} is equal to {1} {2}..
        /// </summary>
        internal static string PurchaseOrder_ExchangeRate {
            get {
                return ResourceManager.GetString("PurchaseOrder_ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following invoice budget items have exceeded its original budget amount for the financial year:.
        /// </summary>
        internal static string PurchaseOrder_InvoiceBudgetNotEqual {
            get {
                return ResourceManager.GetString("PurchaseOrder_InvoiceBudgetNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter of Award.
        /// </summary>
        internal static string PurchaseOrder_LetterOfAward {
            get {
                return ResourceManager.GetString("PurchaseOrder_LetterOfAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        internal static string PurchaseOrder_PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder_PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request for quotation should be raised before this PO..
        /// </summary>
        internal static string PurchaseOrder_RFQToPOPreferred {
            get {
                return ResourceManager.GetString("PurchaseOrder_RFQToPOPreferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request for quotation must be raised before this PO. You cannot submit this PO for approval..
        /// </summary>
        internal static string PurchaseOrder_RFQToPORequired {
            get {
                return ResourceManager.GetString("PurchaseOrder_RFQToPORequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar.
        /// </summary>
        internal static string ReceiptMode_Dollar {
            get {
                return ResourceManager.GetString("ReceiptMode_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string ReceiptMode_Quantity {
            get {
                return ResourceManager.GetString("ReceiptMode_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextTree.
        /// </summary>
        internal static string ReportFieldControlType_ContextTree {
            get {
                return ResourceManager.GetString("ReportFieldControlType_ContextTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ReportFieldControlType_Date {
            get {
                return ResourceManager.GetString("ReportFieldControlType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        internal static string ReportFieldControlType_DateTime {
            get {
                return ResourceManager.GetString("ReportFieldControlType_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown List.
        /// </summary>
        internal static string ReportFieldControlType_DropdownList {
            get {
                return ResourceManager.GetString("ReportFieldControlType_DropdownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Month Year.
        /// </summary>
        internal static string ReportFieldControlType_MonthYear {
            get {
                return ResourceManager.GetString("ReportFieldControlType_MonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiSelect List.
        /// </summary>
        internal static string ReportFieldControlType_MultiSelectList {
            get {
                return ResourceManager.GetString("ReportFieldControlType_MultiSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Button List.
        /// </summary>
        internal static string ReportFieldControlType_RadioButtonList {
            get {
                return ResourceManager.GetString("ReportFieldControlType_RadioButtonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Box.
        /// </summary>
        internal static string ReportFieldControlType_TextBox {
            get {
                return ResourceManager.GetString("ReportFieldControlType_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***IPT Vendor Selected***.
        /// </summary>
        internal static string RequestForQuotation_AwardedIPTVendorMessageTitleIndication {
            get {
                return ResourceManager.GetString("RequestForQuotation_AwardedIPTVendorMessageTitleIndication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget {0}.
        /// </summary>
        internal static string RequestForQuotation_EntireNotMatch {
            get {
                return ResourceManager.GetString("RequestForQuotation_EntireNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Item Number {0}.
        /// </summary>
        internal static string RequestForQuotation_LineNotMatch {
            get {
                return ResourceManager.GetString("RequestForQuotation_LineNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest.
        /// </summary>
        internal static string RequestForQuotation_Lowest {
            get {
                return ResourceManager.GetString("RequestForQuotation_Lowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;font style=&apos;color:Red; font-weight:Bold&apos;&gt;A minimum of {0} quotations is preferred for this request for quotation.&lt;/font&gt;.
        /// </summary>
        internal static string RequestForQuotation_MinimumQuotationsPreferred {
            get {
                return ResourceManager.GetString("RequestForQuotation_MinimumQuotationsPreferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;font style=&apos;color:Red; font-weight:Bold&apos;&gt;A minimum of {0} quotations is required for this request for quotation. You cannot submit for approval until you satisfy this requirement.&lt;/font&gt;.
        /// </summary>
        internal static string RequestForQuotation_MinimumQuotationsRequired {
            get {
                return ResourceManager.GetString("RequestForQuotation_MinimumQuotationsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the WJ.
        /// </summary>
        internal static string RequestForQuotation_RFQ {
            get {
                return ResourceManager.GetString("RequestForQuotation_RFQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increments Forever.
        /// </summary>
        internal static string RunningNumberGenerator_IncrementForever {
            get {
                return ResourceManager.GetString("RunningNumberGenerator_IncrementForever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Location/Equipment code added.
        /// </summary>
        internal static string RunningNumberGenerator_LocationEquipment0 {
            get {
                return ResourceManager.GetString("RunningNumberGenerator_LocationEquipment0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either Location/Equipment code added.
        /// </summary>
        internal static string RunningNumberGenerator_LocationEquipment1 {
            get {
                return ResourceManager.GetString("RunningNumberGenerator_LocationEquipment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Location code added.
        /// </summary>
        internal static string RunningNumberGenerator_LocationEquipment2 {
            get {
                return ResourceManager.GetString("RunningNumberGenerator_LocationEquipment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets Every Month.
        /// </summary>
        internal static string RunningNumberGenerator_ResetEveryMonth {
            get {
                return ResourceManager.GetString("RunningNumberGenerator_ResetEveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets Every Year.
        /// </summary>
        internal static string RunningNumberGenerator_ResetEveryYear {
            get {
                return ResourceManager.GetString("RunningNumberGenerator_ResetEveryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset every year include current year/month.
        /// </summary>
        internal static string RunningNumberGenerator_ResetEveryYearIncCurrentYearMonth {
            get {
                return ResourceManager.GetString("RunningNumberGenerator_ResetEveryYearIncCurrentYearMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        internal static string Source_Direct {
            get {
                return ResourceManager.GetString("Source_Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC.
        /// </summary>
        internal static string Source_OPCServer {
            get {
                return ResourceManager.GetString("Source_OPCServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDA.
        /// </summary>
        internal static string Source_PDA {
            get {
                return ResourceManager.GetString("Source_PDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string Source_Work {
            get {
                return ResourceManager.GetString("Source_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-generated adjustment for Stocktake #0000000.
        /// </summary>
        internal static string StockTake_AutoGeneratedAdjustment {
            get {
                return ResourceManager.GetString("StockTake_AutoGeneratedAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string StoreAdjustItem_Down {
            get {
                return ResourceManager.GetString("StoreAdjustItem_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string StoreAdjustItem_Up {
            get {
                return ResourceManager.GetString("StoreAdjustItem_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to adjust batch item as the resulting quantity is less than zero..
        /// </summary>
        internal static string StoreBinItem_UnableToAdjust {
            get {
                return ResourceManager.GetString("StoreBinItem_UnableToAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string StoreType_IssueLocation {
            get {
                return ResourceManager.GetString("StoreType_IssueLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string StoreType_Storeroom {
            get {
                return ResourceManager.GetString("StoreType_Storeroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Survey_EvaluatedPartyError {
            get {
                return ResourceManager.GetString("Survey_EvaluatedPartyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.A..
        /// </summary>
        internal static string Survey_EvaluatedPartyNull {
            get {
                return ResourceManager.GetString("Survey_EvaluatedPartyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User,
        ///
        ///Please be reminded to click on the following URL to complete the online evaluation form.
        ///
        ///{0}
        ///
        ///Please submit by end of {1}.
        ///
        ///Thank you.
        ///
        ///This is a computer-generated email, please do not reply to this email address. If you have any enquiries, please email to:
        ///
        ///moe_fdd_pdm_surveys@moe.gov.sg
        ///
        ///
        ///P.S.: Please copy the URL and paste it into your browser address bar if the online evaluation form can not be opened by clicking on the URL..
        /// </summary>
        internal static string SurveyPlanner_RemindRespondent_Body {
            get {
                return ResourceManager.GetString("SurveyPlanner_RemindRespondent_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Gentle Reminder - For {1}).
        /// </summary>
        internal static string SurveyPlanner_RemindRespondent_Subject {
            get {
                return ResourceManager.GetString("SurveyPlanner_RemindRespondent_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User,
        ///
        ///The survey has been closed.
        ///
        ///Thank you.
        ///
        ///This is a computer-generated email, please do not reply to this email address. If you have any enquiries, please email to:
        ///
        ///moe_fdd_pdm_surveys@moe.gov.sg.
        /// </summary>
        internal static string SurveyPlanner_SurveyClosed_Body {
            get {
                return ResourceManager.GetString("SurveyPlanner_SurveyClosed_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Closed -  For {1}).
        /// </summary>
        internal static string SurveyPlanner_SurveyClosed_Subject {
            get {
                return ResourceManager.GetString("SurveyPlanner_SurveyClosed_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User,
        ///
        ///We have extended the Survey Submission date to {0}.
        ///
        ///Please click on the following URL to complete the online evaluation form.
        ///
        ///{1}
        ///
        ///Please submit by end of {2}.
        ///
        ///Thank you.
        ///
        ///This is a computer-generated email, please do not reply to this email address. If you have any enquiries, please email to:
        ///
        ///moe_fdd_pdm_surveys@moe.gov.sg
        ///
        ///
        ///P.S.: Please copy the URL and paste it into your browser address bar if the online evaluation form can not be opened by clicking on the URL..
        /// </summary>
        internal static string SurveyPlanner_SurveyExtended_Body {
            get {
                return ResourceManager.GetString("SurveyPlanner_SurveyExtended_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Survey Submission Date Extended - For {1}).
        /// </summary>
        internal static string SurveyPlanner_SurveyExtended_Subject {
            get {
                return ResourceManager.GetString("SurveyPlanner_SurveyExtended_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User,
        ///
        ///Please click on the following URL to complete the online evaluation form.
        ///
        ///{0}
        ///
        ///Please submit by end of {1}.
        ///
        ///Thank you.
        ///
        ///This is a computer-generated email, please do not reply to this email address. If you have any enquiries, please email to:
        ///
        ///moe_fdd_pdm_surveys@moe.gov.sg
        ///
        ///
        ///P.S.: Please copy the URL and paste it into your browser address bar if the online evaluation form can not be opened by clicking on the URL..
        /// </summary>
        internal static string SurveyPlanner_SurveyStarted_Body {
            get {
                return ResourceManager.GetString("SurveyPlanner_SurveyStarted_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (For {1}).
        /// </summary>
        internal static string SurveyPlanner_SurveyStarted_Subject {
            get {
                return ResourceManager.GetString("SurveyPlanner_SurveyStarted_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys for Services provided by Contracted Vendors.
        /// </summary>
        internal static string SurveyPortfolio_ContractedVendor {
            get {
                return ResourceManager.GetString("SurveyPortfolio_ContractedVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys for Services provided by Contracted Vendors evaluated by Managing Agents.
        /// </summary>
        internal static string SurveyPortfolio_ContractedVendorByMA {
            get {
                return ResourceManager.GetString("SurveyPortfolio_ContractedVendorByMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string SurveyPortfolio_Error {
            get {
                return ResourceManager.GetString("SurveyPortfolio_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys for Other Reasons.
        /// </summary>
        internal static string SurveyPortfolio_OtherReasons {
            get {
                return ResourceManager.GetString("SurveyPortfolio_OtherReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Definition Language.
        /// </summary>
        internal static string TemplateType_Rdl {
            get {
                return ResourceManager.GetString("TemplateType_Rdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Reports.
        /// </summary>
        internal static string TemplateType_Rpt {
            get {
                return ResourceManager.GetString("TemplateType_Rpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days .
        /// </summary>
        internal static string Time_DaysPlural {
            get {
                return ResourceManager.GetString("Time_DaysPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day .
        /// </summary>
        internal static string Time_DaysSingular {
            get {
                return ResourceManager.GetString("Time_DaysSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} later.
        /// </summary>
        internal static string Time_Future {
            get {
                return ResourceManager.GetString("Time_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours .
        /// </summary>
        internal static string Time_HoursPlural {
            get {
                return ResourceManager.GetString("Time_HoursPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour .
        /// </summary>
        internal static string Time_HoursSingular {
            get {
                return ResourceManager.GetString("Time_HoursSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes .
        /// </summary>
        internal static string Time_MinutesPlural {
            get {
                return ResourceManager.GetString("Time_MinutesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute .
        /// </summary>
        internal static string Time_MinutesSingular {
            get {
                return ResourceManager.GetString("Time_MinutesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moments.
        /// </summary>
        internal static string Time_MomentsAgo {
            get {
                return ResourceManager.GetString("Time_MomentsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0} months.
        /// </summary>
        internal static string Time_MonthPlural {
            get {
                return ResourceManager.GetString("Time_MonthPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        internal static string Time_Now {
            get {
                return ResourceManager.GetString("Time_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ago.
        /// </summary>
        internal static string Time_Past {
            get {
                return ResourceManager.GetString("Time_Past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds .
        /// </summary>
        internal static string Time_SecondsPlural {
            get {
                return ResourceManager.GetString("Time_SecondsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} second .
        /// </summary>
        internal static string Time_SecondsSingular {
            get {
                return ResourceManager.GetString("Time_SecondsSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0} years.
        /// </summary>
        internal static string Time_YearPlural {
            get {
                return ResourceManager.GetString("Time_YearPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0} year.
        /// </summary>
        internal static string Time_YearSingular {
            get {
                return ResourceManager.GetString("Time_YearSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string TimeUnit_Days {
            get {
                return ResourceManager.GetString("TimeUnit_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string TimeUnit_Days1 {
            get {
                return ResourceManager.GetString("TimeUnit_Days1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string TimeUnit_Hours {
            get {
                return ResourceManager.GetString("TimeUnit_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string TimeUnit_Hours1 {
            get {
                return ResourceManager.GetString("TimeUnit_Hours1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string TimeUnit_Minutes {
            get {
                return ResourceManager.GetString("TimeUnit_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string TimeUnit_Minutes1 {
            get {
                return ResourceManager.GetString("TimeUnit_Minutes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string TimeUnit_Month {
            get {
                return ResourceManager.GetString("TimeUnit_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string TimeUnit_Months {
            get {
                return ResourceManager.GetString("TimeUnit_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string TimeUnit_Months1 {
            get {
                return ResourceManager.GetString("TimeUnit_Months1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        internal static string TimeUnit_Quarter {
            get {
                return ResourceManager.GetString("TimeUnit_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string TimeUnit_Week {
            get {
                return ResourceManager.GetString("TimeUnit_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        internal static string TimeUnit_Weeks {
            get {
                return ResourceManager.GetString("TimeUnit_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        internal static string TimeUnit_Weeks1 {
            get {
                return ResourceManager.GetString("TimeUnit_Weeks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string TimeUnit_Year {
            get {
                return ResourceManager.GetString("TimeUnit_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string TimeUnit_Years {
            get {
                return ResourceManager.GetString("TimeUnit_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string TimeUnit_Years1 {
            get {
                return ResourceManager.GetString("TimeUnit_Years1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust.
        /// </summary>
        internal static string TransactionType_Adjust {
            get {
                return ResourceManager.GetString("TransactionType_Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        internal static string TransactionType_CheckIn {
            get {
                return ResourceManager.GetString("TransactionType_CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string TransactionType_CheckOut {
            get {
                return ResourceManager.GetString("TransactionType_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string TransactionType_Issue {
            get {
                return ResourceManager.GetString("TransactionType_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        internal static string TransactionType_Receive {
            get {
                return ResourceManager.GetString("TransactionType_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string TransactionType_Return {
            get {
                return ResourceManager.GetString("TransactionType_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store-to-Store Transfer.
        /// </summary>
        internal static string TransactionType_StoreTransfer {
            get {
                return ResourceManager.GetString("TransactionType_StoreTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string TriggeringEventName_Approve {
            get {
                return ResourceManager.GetString("TriggeringEventName_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported.
        /// </summary>
        internal static string TriggeringEventName_Approve_Supporter {
            get {
                return ResourceManager.GetString("TriggeringEventName_Approve_Supporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string TriggeringEventName_Reject {
            get {
                return ResourceManager.GetString("TriggeringEventName_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string UnitOfMeasureText_Hour {
            get {
                return ResourceManager.GetString("UnitOfMeasureText_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string WhereUsed_General {
            get {
                return ResourceManager.GetString("WhereUsed_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Assigned Workflow Recipients.
        /// </summary>
        internal static string WhereUsed_NotifyAssignedWorkflowRecipients {
            get {
                return ResourceManager.GetString("WhereUsed_NotifyAssignedWorkflowRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 (Lowest).
        /// </summary>
        internal static string Work_Priority0 {
            get {
                return ResourceManager.GetString("Work_Priority0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Work_Priority1 {
            get {
                return ResourceManager.GetString("Work_Priority1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Work_Priority2 {
            get {
                return ResourceManager.GetString("Work_Priority2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 (Highest).
        /// </summary>
        internal static string Work_Priority3 {
            get {
                return ResourceManager.GetString("Work_Priority3", resourceCulture);
            }
        }
    }
}
