//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkflowStates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkflowStates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicLayer.Resources.WorkflowStates", typeof(WorkflowStates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        internal static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending for Transfer.
        /// </summary>
        internal static string ApprovedForTransfer {
            get {
                return ResourceManager.GetString("ApprovedForTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Awarded {
            get {
                return ResourceManager.GetString("Awarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled and Revised.
        /// </summary>
        internal static string CancelledAndRevised {
            get {
                return ResourceManager.GetString("CancelledAndRevised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committed.
        /// </summary>
        internal static string Committed {
            get {
                return ResourceManager.GetString("Committed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Progress.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Adjustment.
        /// </summary>
        internal static string PendingAdjustment {
            get {
                return ResourceManager.GetString("PendingAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval.
        /// </summary>
        internal static string PendingApproval {
            get {
                return ResourceManager.GetString("PendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Invoice Approval.
        /// </summary>
        internal static string PendingApproval_Invoice {
            get {
                return ResourceManager.GetString("PendingApproval_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Assignment.
        /// </summary>
        internal static string PendingAssignment {
            get {
                return ResourceManager.GetString("PendingAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Cancellation and Revised.
        /// </summary>
        internal static string PendingCancelAndRevised {
            get {
                return ResourceManager.GetString("PendingCancelAndRevised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Cancellation.
        /// </summary>
        internal static string PendingCancellation {
            get {
                return ResourceManager.GetString("PendingCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Checkout.
        /// </summary>
        internal static string PendingCheckout {
            get {
                return ResourceManager.GetString("PendingCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Closure.
        /// </summary>
        internal static string PendingClosure {
            get {
                return ResourceManager.GetString("PendingClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Contractor.
        /// </summary>
        internal static string PendingContractor {
            get {
                return ResourceManager.GetString("PendingContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Evaluation.
        /// </summary>
        internal static string PendingEvaluation {
            get {
                return ResourceManager.GetString("PendingEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Execution.
        /// </summary>
        internal static string PendingExecution {
            get {
                return ResourceManager.GetString("PendingExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Helpdesk.
        /// </summary>
        internal static string PendingHelpdesk {
            get {
                return ResourceManager.GetString("PendingHelpdesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Invitation.
        /// </summary>
        internal static string PendingInvitation {
            get {
                return ResourceManager.GetString("PendingInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Material.
        /// </summary>
        internal static string PendingMaterial {
            get {
                return ResourceManager.GetString("PendingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Planning.
        /// </summary>
        internal static string PendingPlanning {
            get {
                return ResourceManager.GetString("PendingPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Quotation.
        /// </summary>
        internal static string PendingQuotation {
            get {
                return ResourceManager.GetString("PendingQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Receipt.
        /// </summary>
        internal static string PendingReceipt {
            get {
                return ResourceManager.GetString("PendingReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Return.
        /// </summary>
        internal static string PendingReturn {
            get {
                return ResourceManager.GetString("PendingReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected for Redraft.
        /// </summary>
        internal static string RejectedforRedraft {
            get {
                return ResourceManager.GetString("RejectedforRedraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected for Rework.
        /// </summary>
        internal static string RejectedforRework {
            get {
                return ResourceManager.GetString("RejectedforRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated.
        /// </summary>
        internal static string Terminated {
            get {
                return ResourceManager.GetString("Terminated", resourceCulture);
            }
        }
    }
}
