//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoleNameResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoleNameResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataMigration.RoleNameResource", typeof(RoleNameResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Administrator.
        /// </summary>
        internal static string ADMIN {
            get {
                return ResourceManager.GetString("ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Administrator.
        /// </summary>
        internal static string APPLICATIONADMIN {
            get {
                return ResourceManager.GetString("APPLICATIONADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Administrator.
        /// </summary>
        internal static string ASSETADMIN {
            get {
                return ResourceManager.GetString("ASSETADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Administrator.
        /// </summary>
        internal static string BUDGETADMIN {
            get {
                return ResourceManager.GetString("BUDGETADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Approver.
        /// </summary>
        internal static string BUDGETAPPROVER {
            get {
                return ResourceManager.GetString("BUDGETAPPROVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Viewer.
        /// </summary>
        internal static string BUDGETVIEWER {
            get {
                return ResourceManager.GetString("BUDGETVIEWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Purchaser.
        /// </summary>
        internal static string CENTRALPURCHASER {
            get {
                return ResourceManager.GetString("CENTRALPURCHASER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Administrator.
        /// </summary>
        internal static string CONTRACTADMIN {
            get {
                return ResourceManager.GetString("CONTRACTADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Administrator.
        /// </summary>
        internal static string DASHBOARDADMIN {
            get {
                return ResourceManager.GetString("DASHBOARDADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Administrator.
        /// </summary>
        internal static string DMADMIN {
            get {
                return ResourceManager.GetString("DMADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Administrator.
        /// </summary>
        internal static string EQUIPMENTADMINISTRATOR {
            get {
                return ResourceManager.GetString("EQUIPMENTADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        internal static string FINANCE {
            get {
                return ResourceManager.GetString("FINANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Officer.
        /// </summary>
        internal static string FINANCEOFFICER {
            get {
                return ResourceManager.GetString("FINANCEOFFICER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Manager.
        /// </summary>
        internal static string INVENTORYMANAGER {
            get {
                return ResourceManager.GetString("INVENTORYMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        internal static string PROJECTMANAGER {
            get {
                return ResourceManager.GetString("PROJECTMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Administrator.
        /// </summary>
        internal static string PURCHASEADMIN {
            get {
                return ResourceManager.GetString("PURCHASEADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Approver.
        /// </summary>
        internal static string PURCHASEAPPROVER {
            get {
                return ResourceManager.GetString("PURCHASEAPPROVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Requestor.
        /// </summary>
        internal static string PURCHASEREQUESTOR {
            get {
                return ResourceManager.GetString("PURCHASEREQUESTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Verification Officer.
        /// </summary>
        internal static string PURCHASEVERIFICATIONOFFICER {
            get {
                return ResourceManager.GetString("PURCHASEVERIFICATIONOFFICER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Administrator.
        /// </summary>
        internal static string REPORTADMIN {
            get {
                return ResourceManager.GetString("REPORTADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident.
        /// </summary>
        internal static string RESIDENT {
            get {
                return ResourceManager.GetString("RESIDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Manager.
        /// </summary>
        internal static string SERVICEMANAGER {
            get {
                return ResourceManager.GetString("SERVICEMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Vendor.
        /// </summary>
        internal static string SERVICEVENDOR {
            get {
                return ResourceManager.GetString("SERVICEVENDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Administrator.
        /// </summary>
        internal static string SYSTEMADMIN {
            get {
                return ResourceManager.GetString("SYSTEMADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Administrator.
        /// </summary>
        internal static string USERADMIN {
            get {
                return ResourceManager.GetString("USERADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Administrator.
        /// </summary>
        internal static string VENDORADMIN {
            get {
                return ResourceManager.GetString("VENDORADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Approver.
        /// </summary>
        internal static string WORKAPPROVER {
            get {
                return ResourceManager.GetString("WORKAPPROVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller.
        /// </summary>
        internal static string WORKCALLER {
            get {
                return ResourceManager.GetString("WORKCALLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpdesk.
        /// </summary>
        internal static string WORKHELPDESK {
            get {
                return ResourceManager.GetString("WORKHELPDESK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Request Supervisor.
        /// </summary>
        internal static string WORKREQUESTSUPERVISOR {
            get {
                return ResourceManager.GetString("WORKREQUESTSUPERVISOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Officer.
        /// </summary>
        internal static string WORKSUPERVISOR {
            get {
                return ResourceManager.GetString("WORKSUPERVISOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        internal static string WORKTECHNICIAN {
            get {
                return ResourceManager.GetString("WORKTECHNICIAN", resourceCulture);
            }
        }
    }
}
