//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataMigration.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Catalogue Type.
        /// </summary>
        internal static string Catalogue_Root {
            get {
                return ResourceManager.GetString("Catalogue_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檢查組.
        /// </summary>
        internal static string CheckList_Group {
            get {
                return ResourceManager.GetString("CheckList_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string CheckList_Others {
            get {
                return ResourceManager.GetString("CheckList_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string CheckList_Remarks {
            get {
                return ResourceManager.GetString("CheckList_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檢查類型.
        /// </summary>
        internal static string CheckList_Type {
            get {
                return ResourceManager.GetString("CheckList_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設備組.
        /// </summary>
        internal static string EquipmentType_Group {
            get {
                return ResourceManager.GetString("EquipmentType_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設備類型.
        /// </summary>
        internal static string EquipmentType_Type {
            get {
                return ResourceManager.GetString("EquipmentType_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物料.
        /// </summary>
        internal static string IS_Catalogue {
            get {
                return ResourceManager.GetString("IS_Catalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 組名.
        /// </summary>
        internal static string NOT_Catalogue {
            get {
                return ResourceManager.GetString("NOT_Catalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作类型.
        /// </summary>
        internal static string TypeOfWorkRootName {
            get {
                return ResourceManager.GetString("TypeOfWorkRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        internal static string Types_Others {
            get {
                return ResourceManager.GetString("Types_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitOfMeasure.
        /// </summary>
        internal static string UnitOfMeasureRootName {
            get {
                return ResourceManager.GetString("UnitOfMeasureRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitOfMeasure.
        /// </summary>
        internal static string UnitOfMeasureTypeName {
            get {
                return ResourceManager.GetString("UnitOfMeasureTypeName", resourceCulture);
            }
        }
    }
}
